#pragma once

#ifndef CL_USE_DEPRECATED_OPENCL_1_2_APIS
#define CL_USE_DEPRECATED_OPENCL_1_2_APIS
#endif // CL_USE_DEPRECATED_OPENCL_1_2_APIS

#ifndef CL_TARGET_OPENCL_VERSION
#define CL_TARGET_OPENCL_VERSION 120
#endif // CL_TARGET_OPENCL_VERSION

#include <CL/cl.h>
#include <memory>
#include <string>
#include <vector>

#include "cuboid.hpp"
#include "level.hpp"
#include "mgcl.hpp"
#include "multigrid_engine.hpp"
#include "opencl_helper.hpp"
#include "stencil.hpp"

namespace mgcl
{
    // forward declarations
    class Level;

    /**
     * @brief Main interface class for using mgcl. Defines all the parameters which can be set using the appropriate
     * setters. The problem is then solved using solve (using OpenCL if use_opencl is true, otherwise sequentially).
     * If an OpenCLEnvironment shall be reused, reuseOpenCL can be used.
     *
     */
    class Problem
    {
    private:
        /* initial solution and right hand side vectors */
        std::shared_ptr<Cuboid> v = nullptr; /* can be ommited if device buffers are supplied */
        std::shared_ptr<Cuboid> f = nullptr; /* can be ommited if device buffers are supplied */

        /* Buffers for v and f. Only need to be set if buffers already exist on device and should be reused */
        cl_mem dV = nullptr;
        cl_mem dF = nullptr;
        cl_mem dStencilValues = nullptr;

        /* grid dimensions */
        int m;
        int n;
        int o;

        /* Holds level-dependent data for each level */
        std::vector<std::shared_ptr<Level>> levels;

        // TODO check what happens when reuse_buffer and ghosts != ghosts_in
        /* Amount of ghost cells surrounding v and f. If optimized jacobi shall be used it must be greater or equal than
         * max(nu1, nu2). Must fit to buffers ghosts size if reuse_opencl_buffers is set. Defaults to 1. */
        int ghosts = 1;

        /* Amount of ghost cells of input data. Defaults to 0. Only relevant if buffers are not reused. */
        int ghosts_in = 0;

        /* maximum grid level, starting from 0 as the finest level */
        int maxlevel = -1;

        /* maximum v-cycle iteration count */
        int maxiter_vcycles = 5;

        /* pre and post smoothing steps */
        int nu1 = 2;
        int nu2 = 2;

        /* damping factor */
        double omega = 0.8;

        /* tolerance */
        double tol = 1e-7;

        /* If true, tolerance will be ignored, thus maxiter_vcycles v-cycle iterations will be done for sure.
         * Defaults to false.
         * Set this to true if you are using OpenCL and don't need to know the relative residual each v-cycle iteration. */
        bool ignoreTol = false;

        /* Type of norm of the residual which will be used as termination criterium */
        MGCL_RESIDUAL_NORM residual_norm = MGCL_L2;

        /* Stencil that will be used in Jacobi's method */
        std::shared_ptr<Stencil> stencil = nullptr;

        /* Whether to use opencl or not. Defaults to 0 (not using opencl) */
        // TODO needed?
        bool use_opencl = false;

        /* Whether to reuse opencl buffers, context and commands or not. Defaults to 0 (not reusing opencl buffers).
         * Provided buffers must have size of ghosted grid, e.g. (m+2*ghosts) * (n+2*ghosts) * (o+2*ghosts) */
        bool reuse_opencl_buffers = false;

        /* If true input data from d_v and d_f will be copied to newly created buffers, respecting the nearfield ghost cell
         * amount. Defaults to 0. */
        bool copy_buffer_data = false;

        /* If true, resulting v is read from device to host when mgcl has finished. Defaults to 0 (not reading results). */
        bool read_results = false;

        /* If true, optimized jacobi version is used which calculates multiple iterations in one kernel call using local
         * memory. ghosts must be equal to iteration count per kernel call which is limited by local memory size of the
         * device. Defaults to false. */
        bool use_local_memory = false;

        /* Preferred work-group size in x-dimension for jacobi smoother. Defaults to 16. */
        int jacobi_wg_size_x = 16;

        /* Preferred work-group size in y-dimension for jacobi smoother. Defaults to 16. */
        int jacobi_wg_size_y = 16;

        /* Preferred iterations per jacobi kernel call. Is only used when use_local_memory is true. Defaults to 3.
         * Gets automatically decreased if nu1, nu2 or ghosts are smaller. */
        int jacobi_iterations_per_kernel = 3;

        /* If true, no output will be generated by mgcl. */
        bool silent = false;

        /* Manages OpenCL stuff */
        OpenCLHelper openCLHelper;

        friend class OpenCLHelper;
        friend class Level;
        friend class MultigridEngine;

    public:
        Problem(int m_, int n_, int o_);
        Problem(int m_, int n_, int o_, Cuboid *f_, Cuboid *v_);
        Problem(int m_, int n_, int o_, std::shared_ptr<Cuboid> f_, std::shared_ptr<Cuboid> v_);
        Problem(int m_, int n_, int o_, cl_mem d_f_, cl_mem d_v_);
        Problem(const Problem &) = delete;
        Problem &operator=(const Problem &) = delete;
        Problem(const Problem &&) = delete;
        Problem &operator=(const Problem &&) = delete;
        ~Problem() = default;

        bool checkParameters();
        int calculateAndSetMaxLevel();
        bool init();

        int reuseOpenCL(cl_context context, cl_command_queue commandQueue, cl_device_id deviceId);
        int initOpenCL();
        int readResults();

        void solve();
        void solveSeq();

        Level &getLevelAt(int index) const;
        int getLevelsSize() const;

        /********************************
         * Getters and Setters
         ********************************/

        Cuboid &getV() const;
        std::shared_ptr<Cuboid> getVPtr() const;
        void setV(std::shared_ptr<Cuboid> v_);

        Cuboid &getF() const;
        std::shared_ptr<Cuboid> getFPtr() const;
        void setF(std::shared_ptr<Cuboid> f_);

        int getM() const;

        int getN() const;

        int getO() const;

        int getGhosts() const;
        void setGhosts(int ghosts_);

        int getGhostsIn() const;
        void setGhostsIn(int ghostsIn);

        int getMaxlevel() const;
        void setMaxlevel(int maxlevel_);

        int getMaxiterVcycles() const;
        void setMaxiterVcycles(int maxiterVcycles);

        int getNu1() const;
        void setNu1(int nu1_);

        int getNu2() const;
        void setNu2(int nu2_);

        double getOmega() const;
        void setOmega(double omega_);

        double getTol() const;
        void setTol(double tol_);

        MGCL_RESIDUAL_NORM getResidualNorm() const;
        void setResidualNorm(const MGCL_RESIDUAL_NORM &residualNorm);

        std::shared_ptr<Stencil> getStencil() const;
        void setStencil(std::shared_ptr<Stencil> stencil_);

        bool getReuseOpenclBuffers() const;
        void setReuseOpenclBuffers(bool reuseOpenclBuffers);

        bool getCopyBufferData() const;
        void setCopyBufferData(bool copyBufferData);

        bool getReadResults() const;
        void setReadResults(bool readResults);

        bool getUseLocalMemory() const;
        void setUseLocalMemory(bool useLocalMemory);

        int getJacobiWgSizeX() const;
        void setJacobiWgSizeX(int jacobiWgSizeX);

        int getJacobiWgSizeY() const;
        void setJacobiWgSizeY(int jacobiWgSizeY);

        int getJacobiIterationsPerKernel() const;
        void setJacobiIterationsPerKernel(int jacobiIterationsPerKernel);

        bool getUseOpencl() const;
        void setUseOpencl(bool useOpencl);

        cl_mem getDStencilValues() const;
        void setDStencilValues(const cl_mem &dStencilValues);

        cl_mem getDV() const;
        void setDV(const cl_mem &dV_);

        cl_mem getDF() const;
        void setDF(const cl_mem &dF_);

        OpenCLHelper &getOpenCLHelper();

        std::string getKernelDir() const;
        void setKernelDir(const std::string &kernelDir_);

        std::string getDeviceName() const;
        void setDeviceName(const std::string &deviceName_);

        cl_device_type getDeviceType() const;
        void setDeviceType(const cl_device_type &deviceType_);

        cl_device_id getDeviceId() const;

        cl_context getContext() const;

        cl_command_queue getCommands() const;

        cl_program getProgram() const;

        bool getSilent() const;
        void setSilent(bool silent_);

        bool getIgnoreTol() const;
        void setIgnoreTol(bool ignoreTol_);
    };
}